version: "3.7"

x-logging: &default-logging
  driver: "local"
  options:
    max-size: "20m"
    max-file: "5"

volumes:
  postgres_data:

services:
  controller:
    build: controller
    volumes:
      - ./logs/controller:/app/logs
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 5001:5001
    logging: *default-logging
  getter:
    build: getter
    ports:
      - 4000:4000
    volumes:
      - ./logs/getter:/app/logs
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging: *default-logging
