version: "3"

x-logging: &default-logging
  driver: "local"
  options:
    max-size: "20m"
    max-file: "5"

volumes:
  postgres_data:

networks:
  traefik-net:
    external: true

services:
  usertracker:
    build: .
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "./logs:/usr/app/logs"
    networks:
      - traefik-net
    logging: *default-logging
  postgres-usertracker:
    image: postgres:14
    networks:
      - traefik-net
    restart: unless-stopped
    ports:
      - 5434:5432
    volumes:
      - ./scripts/sql:/docker-entrypoint-initdb.d:ro
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}"]
    user: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    logging: *default-logging
  pgbackups:
    image: kartoza/pg-backup:14-3.2
    restart: always
    logging: *default-logging
    depends_on:
      - postgres-usertracker
    networks:
      - traefik-net
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres-usertracker
    volumes:
      - /var/opt/pgbackups-usertracker:/backups
