version: "3.5"

x-logging: &default-logging
  driver: "local"
  options:
    max-size: "20m"
    max-file: "5"

volumes:
  postgres_data:

services:
  controller:
    build: controller
    volumes:
      - ./logs/controller:/app/logs
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 5001:5000
    logging: *default-logging
  getter:
    build: getter
    ports:
      - 4000:4000
    volumes:
      - ./logs/getter:/app/logs
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging: *default-logging
  postgres:
    image: postgres:14
    restart: unless-stopped
    ports:
      - 5434:5432
    volumes:
      - ./controller/files/scripts/sql:/docker-entrypoint-initdb.d:ro
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}"]
    user: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    logging: *default-logging
